### ISSUE TITLE
genymotion 

### ISSUE THREAD

**Issue by ghost** [necrose99/necromancy-overlay#10]
SRC_URI non exist for genymotion

**Comment by necrose99** [comment]
open-overlay the github user and overlay is gone or made 
however before the devs brought the axe on it, I figured i'd get it and a few more.
layman syncs into gentoo's repo mirrors so I was able to Rescue some of good ebuilds before they got their permanent rest into the neither-winds.  since upstream link for it is now dead , best to try to keep some of them alive... 

**ebuild needs updated to Eclass makeself, or debian unpacker.**

http://files2.genymotion.com/genymotion/genymotion-2.5.2/genymotion-2.5.2_x86.bin
http://files2.genymotion.com/genymotion/genymotion-2.5.2/genymotion-2.5.2_x64_debian.bin

Often the only reader is in android and or wont run cleanly in wine, IE Devry University's ebook service provider , so force to reboot to widoze and fire up vm, for linux, but also to write papers/read the book...

**Comment by Pengyu-wait4it** [comment]
the SRC_URI for gentoo in amd64 has been changed to http://files2.genymotion.com/genymotion/genymotion-2.6.0/genymotion-2.6.0-linux_x64.bin

**Comment by necrose99** [comment]
On Mon, Apr 4, 2016 at 7:56 PM, Pengyu-wait4it notifications@github.com
wrote:

> http://files2.genymotion.com/genymotion/genymotion-2.6.0/genymotion-2.6.0-linux_x64.bin

${P}-linux_x64.bin
​ ,   ​${P}-linux_x86.bin
​   ​

​noted    will do , t'marrow I have the CISSP exam to battle with   ​
pull request for this will be honored
